# Generated by Django 3.1.6 on 2021-02-06 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EvaluacionRipioBackendAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coin',
            old_name='quantity_exists',
            new_name='key',
        ),
    ]
